# Data generation parameters
dt: 0.01
t_train: 5.12
t_val: 5.12
t_test: 10.24
data_split: [0.7, 0.2, 0.1]

# Hyperparameters of Physformer
block_size: 32
num_heads: 4
num_layers: 2
d_model: 32
ffc: 256
weight_decay: 0.001
lr: 0.001
batch_size: 32

# Training loop parameters
num_epochs: 2
optimizer: "ADAM"
model: "base"
lorenz_dim: 3


